task :full_scrape => :environment do
  sets_list = [
  #["Gatecrash", "GTC"],
  #["Return to Ravnica", "RTR"],
  #["Magic 2013", "M13"],
  #["Avacyn Restored", "AVR"],
  #["Dark Ascension", "DKA"],
  #["Innistrad", "ISD"],
  #["Magic 2012", "M12"],
  #["New Phyrexia", "NPH"],
  #["Mirrodin Besieged", "MBS"],
  #["Scars of Mirrodin", "SOM"],
  #["Magic 2011", "M11"],
  #["Rise of the Eldrazi","ROE"],
  #["Worldwake","WWK"],
  #["Zendikar","ZEN"],
  #["Magic 2010", "M10"],
  #["Alara Reborn","ARB"],
  #["Conflux","CON"],
  #["Shards of Alara","ALA"],
  #["Eventide", "EVE"],
  #["Shadowmoor", "SHM"],
  #["Morningtide", "MOR"],
  #["Lorwyn", "LRW"],
  #["Tenth Edition", "10E"],
  #["Future Sight", "FUT"],
  #["Planar Chaos", "PLC"],
  #["Time Spiral", "TSP"],
  #["Coldsnap", "CSP"],
  #["Dissension", "DIS"],
  #["Guildpact", "GPT"],
  #["Ravnica: City of Guilds", "RAV"],
  #["Ninth Edition", "9ED"],
  #["Saviors of Kamigawa", "SOK"],
  #["Betrayers of Kamigawa", "BOK"],
  #["Champions of Kamigawa", "CHK"],
  #["Fifth Dawn", "5DN"],
  #["Darksteel", "DST"],
  #["Mirrodin", "MRD"],
  #["Eighth Edition", "8ED"],
  #["Scourge", "SCG"],
  #["Legions", "LGN"],
  #["Onslaught", "ONS"],
  #["Judgment", "JUD"],
  #["Torment", "TOR"],
  #["Odyssey", "ODY"],
  #["Apocalypse", "APC"],
  #["Seventh Edition", "7ED"],
  #["Planeshift", "PLS"],
  #["Invasion", "INV"],
  #["Prophecy", "PCY"],
  #["Nemesis", "NEM"],
  #["Mercadian Masques", "MMQ"],
  #["Urza's Destiny", "UDS"],
  #["Sixth Edition", "6ED"],
  #["Urza's Legacy", "ULG"],
  ["Urza's Saga", "USG"],
  ["Exodus", "EXO"],
  ["Stronghold", "STH"],
  ["Tempest", "TMP"],
  ["Weatherlight", "WTH"],
  ["Fifth Edition", "5ED"],
  ["Visions", "VIS"],
  ["Mirage", "MIR"],
  ["Alliances", "ALL"],
  ["Homelands", "HML"],
  ["Ice Age", "ICE"],
  ["Fourth Edition", "4ED"],
  ["Fallen Empires", "FEM"],
  ["The Dark", "DRK"],
  ["Legends", "LEG"],
  ["Revised Edition", "3ED"],
  ["Antiquities", "ATQ"],
  ["Arabian Nights", "ARN"],
  ["Unlimited Edition", "2ED"],
  ["Unhinged", "UNH"],
  ["Unglued", "UGL"]
  ]
  sets_list.each do |set|
    GathererSetScraper.new(set[0], set[1]).scrape
    p "#{set[0]} Scraped"
  end
end
